"""Render a :class:`~docpilot.core.pipeline.PipelineReport` as a PR comment."""

from __future__ import annotations

import re
from typing import Optional

from .models import Correction, Mapping, RepairAction
from .pipeline import PipelineReport


def _anchor(heading_path: str) -> str:
    """GitHub-style anchor for the last heading in a path."""
    last = heading_path.split(">")[-1].strip().lower()
    last = re.sub(r"[^a-z0-9\s-]", "", last)
    return last.replace(" ", "-")


def _section_link(corr: Correction, mapping: Mapping, repo_url: str) -> str:
    section = mapping.section_by_id(corr.doc_section_id)
    if section is None:
        return f"`{corr.doc_section_id}`"
    label = f"{section.file_path}#{_anchor(section.heading_path)}"
    if repo_url:
        href = f"{repo_url}/blob/HEAD/{section.file_path}#{_anchor(section.heading_path)}"
        return f"[{label}]({href})"
    return f"`{label}`"


def format_pr_comment(
    report: PipelineReport,
    mapping: Mapping,
    fix_pr_url: str = "",
    fix_pr_number: Optional[int] = None,
    repo_url: str = "",
) -> str:
    """Build the structured DocPilot summary comment."""
    accurate = report.sections_checked - len(report.stale_findings)
    lines = [
        "## DocPilot Report",
        "",
        "| Metric | Count |",
        "|--------|-------|",
        f"| Sections checked | {report.sections_checked} |",
        f"| Verified accurate | {accurate} |",
        f"| Auto-fixed | {len(report.auto_fixed)} |",
        f"| Drafted (review) | {len(report.drafts)} |",
        f"| Flagged for review | {len(report.flagged)} |",
        "",
    ]

    if report.auto_fixed:
        links = ", ".join(_section_link(c, mapping, repo_url) for c in report.auto_fixed)
        pr_ref = ""
        if fix_pr_number:
            pr_ref = f" — see PR #{fix_pr_number}"
        elif fix_pr_url:
            pr_ref = f" — see [fix PR]({fix_pr_url})"
        lines.append(f"**Auto-fixed:** {links}{pr_ref}")

    if report.drafts:
        links = ", ".join(_section_link(c, mapping, repo_url) for c in report.drafts)
        lines.append(f"**Drafted (needs review):** {links}")

    if report.flagged:
        links = ", ".join(_section_link(c, mapping, repo_url) for c in report.flagged)
        lines.append(f"**Needs review:** {links}")

    if not report.stale_findings:
        lines.append("**All checked documentation is up to date.**")

    # Per-finding diagnoses for transparency.
    if report.corrections:
        lines.append("")
        lines.append("<details><summary>Diagnoses</summary>\n")
        for c in report.corrections:
            section = mapping.section_by_id(c.doc_section_id)
            heading = section.heading_path if section else c.doc_section_id
            lines.append(f"- **{heading}** [{c.confidence.value}]: {c.diagnosis}")
        lines.append("\n</details>")

    lines.append("")
    lines.append("<sub>Generated by DocPilot · self-healing technical documentation</sub>")
    return "\n".join(lines)
